### ISSUE TITLE
Missing xfms in neuroimaging example

### ISSUE THREAD

**Issue by DirkZomerdijk** [gallantlab/pyrcca#2]
Hello,

I am working with the vim-2 data in the pyrcca neuroimaging example. The obtained data for three subjects are:

Functional data:
VoxelResponses_subject#.mat
Anatomical data:
S#_anatomy.nii

When i am running the example code i get an error when it tries to obtain the mask.

Mask not found, generating...
Traceback (most recent call last):
  File "/home/c10530274/untitled.py", line 24, in <module>
    mask = cortex.db.get_mask(subjects[subj], xfms[subj], type = 'thick')
  File "/home/c10530274/pycortex/cortex/database.py", line 526, in get_mask
    mask = get_cortical_mask(subject, xfmname, type)
  File "/home/c10530274/pycortex/cortex/utils.py", line 99, in get_cortical_mask
    dist, idx = get_vox_dist(subject, xfmname)
  File "/home/c10530274/pycortex/cortex/utils.py", line 133, in get_vox_dist
    xfm = db.get_xfm(subject, xfmname)
  File "/home/c10530274/pycortex/cortex/database.py", line 433, in get_xfm
    xfmdict = json.load(open(fname))
IOError: [Errno 2] No such file or directory: u'/home/c10530274/pycortex/filestore/db/S1/transforms/S1_xfm/matrices.xfm'
[Finished in 1.6s with exit code 1]

It appears that the subjects's corresponding xfm files are needed to succesfully get the mask.
Maybe i do not fully understand what is happening. Am i missing something? Is there a way to obtain the xfms file containing the xfm for each subject?

The only module i have added to run the formats.pyx file is:
import pyximport
pyximport.install()

Greetings,

Dirk

**Comment by nbilenko** [comment]
Hi Dirk!

Apologies for the delayed reply and thank you for using our data and Pyrcca. These transforms were manually created by aligning the functional and anatomical data for each subject using the Pycortex aligner tool. However, we realize it may be a bit challenging to create the transforms for new Pycortex users, especially since Pycortex docs are under development. So, we will add the transform files to the CRCNS dataset. In the meantime, I can email them them to you directly - just send me a message at nbilenko AT berkeley DOT edu.

Cheers,
Natalia
