### ISSUE TITLE
Could be a tiny error about parameter initialization ?

### ISSUE THREAD

**Issue by IndefiniteCalculus** [gallantlab/pyrcca#21]
Hi, thanks for your effort about implement CCA on python. 
I have found something weird in the initial parameter stage of this project
![image](https://user-images.githubusercontent.com/55014395/111568930-a6725e00-87dc-11eb-8a69-7b83083f3434.png)

the code is:
 numCC = min([k.shape[1] for k in kernel]) if numCC is None else numCC

I assume this code is aim to initial the dimension of projected data as the minimum dimension of input data, but shouldn't the right code be:

numCC = min([k.shape[0] for k in kernel]) if numCC is None else numCC

Looking forward to your reply

**Comment by TomDLT** [comment]
I think you are correct.

In the default case `kernelcca=True`, it does not matter since the kernels are square.
However, when `kernelcca=False`, kernels are transposed from `data`, which is a list of arrays of shape (n_samples, n_features).
So as you said, it should be `numCC = min([k.shape[0] for k in kernel]) if numCC is None else numCC`.
